### ISSUE TITLE
flow chart

### ISSUE THREAD

**Issue by g31marc** [simonvomeyser/social-hatemap#8]
visualizing process of tweet evaluation

**Comment by simonvomeyser** [comment]
![image](https://cloud.githubusercontent.com/assets/10830728/23104472/ccffd64a-f6ce-11e6-82dc-04bd4e73fe92.png)

**Comment by simonvomeyser** [comment]
![image](https://cloud.githubusercontent.com/assets/10830728/23104487/0c93d9f0-f6cf-11e6-87d6-3fabcd3f11b9.png)
